language: python

python:
  - 2.7

sudo: true

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgresql-client-10
      - binutils
      - ibproj-dev
      - gdal-bin

env:
  global:
    - PGPORT=5433  
    - DJANGO=1.11.1

before_install:
  - export DJANGO_SETTINGS_MODULE=config.settings
  - export PYTHONPATH=$HOME/builds/akohli96/AlumMeetup
  - export PIP_USE_MIRRORS=true
  - sudo -u postgres psql -c "CREATE USER testuser WITH PASSWORD 'password'"
  - sudo -u postgres psql -c "ALTER ROLE testuser SUPERUSER"

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

script:
  - python manage.py makemigrations && python manage.py migrate && python manage.py test