# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 11:59
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import meetup.repository.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('public', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('modified', meetup.repository.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2018)])),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Other')], max_length=10)),
                ('school', models.CharField(choices=[(b'AUP', b'Architecture & Urban Planning'), (b'BUS', b'Business'), (b'LAW', b'Law'), (b'INF', b'Information'), (b'LSA', b'Literature, Science, and the Arts')], max_length=50)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetup.Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='guest',
            field=models.ManyToManyField(to='meetup.Profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ManyToManyField(related_name='host_profile', to='meetup.Profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ManyToManyField(to='meetup.Location'),
        ),
    ]
